import {sidebar} from "vuepress-theme-hope";

export default sidebar({
    "/编程语言/c": "structure",
    "/编程语言/C++": "structure",
    "/编程语言/java": "structure",
    "/编程语言/linux": "structure",
    "/编程语言/python": "structure",
    "/编程语言/安卓": "structure",
    "/编程语言/汇编": "structure",
    "/硬件/电路图设计": "structure",
    "/硬件/STM32": "structure",
    "/硬件/ESP": "structure",
    "/硬件/freertos": "structure",
    "/硬件/通信协议": "structure",
    "/硬件/cmake": "structure",
    "/硬件/lvgl": "structure",
    "/硬件/u8g2": "structure",
    "/硬件/QT": "structure",
    "/硬件/linux": "structure",
    "/数据结构和算法/": "structure",
    "/科学基础知识/数学物理": "structure",
    "/科学基础知识/生物化学": "structure",
    "/科学基础知识/英语": "structure",
    "/科学基础知识/人工智能": "structure",
    "/示例": "structure",
    "/软件使用或安装": "structure",
    "/UI设计": "structure",
    "/项目案例": "structure",
});
